eot_calendar/routes.py
from flask import Blueprint, render_template, request, abort, redirect, url_for, jsonify, session
from models import db, Entry
from flask_login import login_required, current_user
from eot_calendar.helpers import generateCalendarHTML, get_restaurant, fetch_restaurant_from_yelp, search_yelp, get_star_ratings_html
from forms import AddEntryForm, EditEntryForm, CalendarMonthYearForm
from datetime import datetime, date
import calendar
from sqlalchemy.sql import func

eot_calendar = Blueprint('calendar', __name__)

@eot_calendar.route('/calendar')
@login_required
def calendar_page():
    year = request.args.get('year')
    month = request.args.get('month')
    if not year and not month:
        # check session if there's month, year
        if session.get('month') and session.get('year'):
            month = session.get('month')
            year = session.get('year')
        else:
            today = date.today()
            year = today.year
            month = today.month

    year = int(year)
    month = int(month)
    
    # keep track of last month and year used
    session['month'] = month
    session['year'] = year
    
    form = CalendarMonthYearForm(month=month, year=year)
    
    range = calendar.monthrange(year, month)
    startdate = date(year, month, 1)
    enddate = date(year, month, range[1])
    
    # get number of restaurants visited by a specific user in date range
    numPlaces = db.session.query(Entry).filter(Entry.user_id==current_user.id, Entry.date.between(startdate, enddate)).distinct(Entry.restaurant_id).count()
    
    # get total spent for user for month
    totalSpent = db.session.query(func.sum(Entry.amount)).filter(Entry.user_id==current_user.id, Entry.date.between(startdate, enddate)).first()[0]
    
    calendarHTML = generateCalendarHTML(current_user.id, year, month)
        
    if not calendarHTML:
        abort(400)
        
    return render_template('calendar.html', calendarHTML=calendarHTML, current_user=current_user, form=form, numPlaces=numPlaces, totalSpent=totalSpent)

@eot_calendar.route('/entries')
@login_required
def add_entry_page():
    form = AddEntryForm()
    
    # if supplying a date prepopulate date
    if request.args.get('date'):
        form.date.data = datetime.strptime(request.args.get('date'), '%Y-%m-%d').date()
    else:
        form.date.data = date.today()
        
    return render_template('entry_add.html', current_user=current_user, form=form)

@eot_calendar.route('/entries', methods=['POST'])
@login_required
def add_entry():
    form = AddEntryForm()
    
    if form.validate_on_submit():
        date = form.date.data
        amount = form.amount.data
        name = form.name.data
        yelp_id = form.yelp_id.data
        
        try:
            restaurant = get_restaurant(db, name, yelp_id)
            new_entry = Entry(date=date, amount=amount, restaurant_id=restaurant.id, user_id=current_user.id)
            db.session.add(new_entry)
            db.session.commit()
            
            # keep track of last month and year used
            session['month'] = date.month
            session['year'] = date.year
            
            return redirect(url_for('calendar.show_entry', entry_id=new_entry.id))
        except Exception as e:
            form.yelp_id.errors.append(str(e))        
        
    return render_template('entry_add.html', current_user=current_user, form=form)

@eot_calendar.route('/entries/<int:entry_id>')
@login_required
def show_entry(entry_id):
    entry = Entry.query.get_or_404(entry_id)
    restaurant = {'name':entry.restaurant.name}
    ratingsHTML = None
    
    recent_entries = db.session.query(Entry).filter(Entry.user_id==current_user.id, Entry.restaurant_id==entry.restaurant_id).order_by(Entry.date.desc()).limit(5).all()
    
    
    yelp_id = entry.restaurant.yelp_id
    if yelp_id:
        response = fetch_restaurant_from_yelp(entry.restaurant.yelp_id)
        restaurant['img_url'] = response.get('image_url')
        restaurant['display_address'] = response.get('location').get('display_address')
        restaurant['phone'] = response.get('display_phone')
        restaurant['ratings'] = response.get('rating')
        restaurant['review_count'] = response.get('review_count')
        restaurant['url'] = response.get('url')
        ratingsHTML = get_star_ratings_html(restaurant['ratings'])
    
    return render_template('entry_show.html', current_user=current_user, restaurant=restaurant, entry=entry, ratingsHTML=ratingsHTML, recent_entries=recent_entries)

@eot_calendar.route('/entries/<int:entry_id>/edit')
@login_required
def edit_entry_page(entry_id):
    entry = Entry.query.get_or_404(entry_id)
    
    if entry.user_id != current_user.id:
        abort(403)
    
    form = EditEntryForm(obj=entry)
    form.name.data = entry.restaurant.name
    form.yelp_id.data = entry.restaurant.yelp_id
    return render_template('entry_edit.html', current_user=current_user, form=form, entry_id=entry.id)

@eot_calendar.route('/entries/<int:entry_id>', methods=['POST'])
@login_required
def edit_entry(entry_id):
    entry = Entry.query.get_or_404(entry_id)
    
    if entry.user_id != current_user.id:
        abort(403)
    
    form = AddEntryForm()
    
    if form.validate_on_submit():
        entry.date = form.date.data
        entry.amount = form.amount.data
        entry.name = form.name.data
        entry.yelp_id = form.yelp_id.data
        
        try:
            restaurant = get_restaurant(db, entry.name, entry.yelp_id)
            entry.restaurant_id = restaurant.id
            db.session.commit()
            
            # keep track of last month and year used
            session['month'] = entry.date.month
            session['year'] = entry.date.year
            
            return redirect(url_for('calendar.show_entry', entry_id=entry.id))
        except Exception as e:
            form.yelp_id.errors.append(str(e))
        
    return render_template('entry_edit.html', current_user=current_user, form=form, entry_id=entry.id)

@eot_calendar.route('/entries/<int:entry_id>/delete', methods=['POST'])
@login_required
def delete_entry(entry_id):
    entry = Entry.query.get_or_404(entry_id)
    
    if entry.user_id != current_user.id:
        abort(403)
    db.session.delete(entry)
    db.session.commit()
    
    return redirect(url_for('calendar.calendar_page'))

@eot_calendar.route('/yelp-search')
def search_yelp_request():
    term = request.args.get('term')
    location = request.args.get('location')
    
    if not term or not location:
        return ("Please supply term and location", 400)
    
    try:
        return jsonify(search_yelp(term, location))
    except Exception as e:
        return (str(e), 500)
    

eot_charts/routes.py
from flask import Blueprint, render_template, request, jsonify
from flask_login import login_required, current_user
from forms import ChartsDateRangeForm
from models import db, Entry, Restaurant
from datetime import datetime, date
from calendar import monthrange
from sqlalchemy.sql import func

eot_charts = Blueprint('eot_charts', __name__)

@eot_charts.route('/charts')
@login_required
def charts_page():
    startdate, enddate = get_start_and_end_date()
    form = ChartsDateRangeForm()
    form.startdate.data = startdate
    form.enddate.data = enddate
    return render_template('charts.html', form=form)

@eot_charts.route('/charts/data')
@login_required
def get_chart_data():
    startdate, enddate = get_start_and_end_date(request.args.get('startdate'), request.args.get('enddate'))
    
    # get all restaurants visited within a certain date range
    rows = db.session.query(Restaurant.name, func.count(Restaurant.name), func.sum(Entry.amount)).join(Entry).filter(Entry.user_id == current_user.id, Entry.date.between(startdate, enddate)).group_by(Restaurant.name).all()
    results = {'visits':[], 'spent':[], 'daily':{}}
    
    numPlaces = len(rows)
    totalSpent = 0
    
    for row in rows:
        restaurant = row[0]
        visits = row[1]
        spent = round(row[2], 2)
        totalSpent += spent
        results['visits'].append({'restaurant':restaurant, 'visits':visits})
        results['spent'].append({'restaurant':restaurant, 'spent':spent})
        
    # get amount spent per day
    rows = db.session.query(Entry.date, func.sum(Entry.amount)).filter(Entry.user_id == current_user.id, Entry.date.between(startdate, enddate)).group_by(Entry.date).order_by(Entry.date.asc()).all()
    
    for row in rows:
        day = row[0].strftime('%Y/%m/%d')
        amount = round(row[1], 2)
        results['daily'][day] = amount
    
    results['numPlaces'] = numPlaces
    results['totalSpent'] = totalSpent
    
    return jsonify(results)
    
def get_start_and_end_date(startdate=None, enddate=None):
    today = datetime.now().date()
    range = monthrange(today.year, today.month)
    
    if not startdate and not enddate:
        startdate = date(today.year, today.month, 1)
        enddate = date(today.year, today.month, range[1])
    else:
        startdate = datetime.strptime(startdate, '%Y-%m-%d').date()
        enddate = datetime.strptime(enddate, '%Y-%m-%d').date()
        
    return startdate, enddate

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" rel='stylesheet'>
    <link href="/static/custom.css" rel="stylesheet">
    <title>Eat Out Tracker</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="{{url_for('home')}}"><i class="fa-solid fa-utensils"></i></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if current_user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('calendar.calendar_page')}}">Calendar</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('calendar.add_entry_page')}}">Add Entry</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('eot_charts.charts_page')}}">Charts</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if not current_user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('auth.login_page')}}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('auth.signup_page')}}">Sign Up</a>
                    </li>
                    {% endif %}
                    {% if current_user.is_authenticated%}
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('auth.profile_page')}}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="{{url_for('auth.logout')}}">Log Out</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% for msg in get_flashed_messages() %}
    <div class="alert alert-warning">{{ msg }}</div>
    {% endfor %}
    <div class="vh-100">
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>

templates/calendar.html
{% extends 'base.html' %}
{% block content %}
<div class="row calendar-view">
    <div class="fixed sidebar p-4 bg-light">
        <form action="" method="GET">        
            <p>
                {{form.month.label}}
                {{form.month(class_="form-select")}}
            </p>
        
            <p>
                {{form.year.label}}
                {{form.year(class_="form-control")}}
            </p>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
        <br>
        <div class="text-secondary">Places Visited</div>
        <p class="h5">{{numPlaces or 0}}</p>
        <div class="text-secondary">Total Spent</div>
        <p class="h5">${{'%0.2f'|format(totalSpent or 0)}}</p>
    </div>
    <div class="col p-5">
        {{ calendarHTML|safe }}
    </div>
</div>
{% endblock %}

templates/charts.html
{% extends 'base.html' %}
{% block content %}
<div class="row calendar-view">
    <div class="fixed sidebar p-4 bg-light vh-100">
        <form action="" method="GET" id="daterange_form">        
            <p>
                {{form.startdate.label}}
                {{form.startdate(class_="form-control")}}
            </p>
        
            <p>
                {{form.enddate.label}}
                {{form.enddate(class_="form-control")}}
            </p>
            <button type="submit" class="btn btn-primary">Update</button>
        </form>
        <br>
        <div class="text-secondary">Places Visited</div>
        <p class="h5" id="num-places">{{numPlaces or 0}}</p>
        <div class="text-secondary">Total Spent</div>
        <p class="h5" id="total-spent">${{'%0.2f'|format(totalSpent or 0)}}</p>
    </div>
    <div class="col p-5">
        <canvas id="dailyExpenditure" class="mb-5"></canvas>
        <canvas id="visits" class="mb-5"></canvas>
        <canvas id="spent" class="mb-5"></canvas>
    </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.6.3.slim.min.js"
  integrity="sha256-ZwqZIVdD3iXNyGHbSYdsmWP//UBokj2FHAxKuSBKDSo="
  crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script src="https://unpkg.com/axios/dist/axios.js"></script>
<script src="/static/eot_charts.js"></script>
{% endblock %}

templates/entry_add.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 entry-form border rounded shadow-sm">
    <h1>Add an Entry</h1>
    <form action="{{url_for('calendar.add_entry')}}" method="POST">
        <div class="form-group">
            {{ form.hidden_tag() }}
        
            <p>
                {{form.date.label}}
                {{form.date(class_="form-control")}}
            </p>
        
            <p>
                {{form.amount.label}}
                {{form.amount(class_="form-control")}}
            </p>
        
            <p>
                {{form.name.label}}
                {{form.name(class_="form-control yelp-param")}}
            </p>

            <p>
                <label for="location">Location (Used for Yelp Search)</label>
                <input class="form-control yelp-param" id="location" placeholder="ie. San Francisco" value="{{current_user.default_location or ""}}"">
                <button type='button' class='btn btn-sm btn-danger my-2' id="search-yelp">Search Yelp</button>
            </p>
        
            <p>
                {{form.yelp_id.label}} 
                {{form.yelp_id(class_="form-control")}}
                {% for error in form.yelp_id.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </p>
        </div>
        <button type="submit" class="btn btn-primary">Add Entry</button>
    </form>
    <div class="modal fade " id="search-yelp-modal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="search-yelp-modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" >Results</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="spinner-border m-5" id="spinner" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <div id="results">
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.6.3.slim.min.js"
  integrity="sha256-ZwqZIVdD3iXNyGHbSYdsmWP//UBokj2FHAxKuSBKDSo="
  crossorigin="anonymous"></script>
<script src="https://unpkg.com/axios/dist/axios.js"></script>
<script src="/static/entry.js"></script>
{% endblock %}

templates/entry_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 entry-form border rounded shadow-sm">
    <h1>Edit Entry</h1>
    <form action="{{url_for('calendar.edit_entry', entry_id=entry_id)}}" method="POST">
        <div class="form-group">
            {{ form.hidden_tag() }}
        
            <p>
                {{form.date.label}}
                {{form.date(class_="form-control")}}
            </p>
        
            <p>
                {{form.amount.label}}
                {{form.amount(class_="form-control")}}
            </p>
        
            <p>
                {{form.name.label}}
                {{form.name(class_="form-control yelp-param")}}
            </p>

            <p>
                <label for="location">Location (Used for Yelp Search)</label>
                <input class="form-control yelp-param" id="location" placeholder="ie. San Francisco" value={{current_user.default_location}}>
                <button type='button' class='btn btn-sm btn-danger my-2' id='search-yelp'>Search Yelp</button>
            </p>
        
            <p>
                {{form.yelp_id.label}} 
                {{form.yelp_id(class_="form-control")}}
                {% for error in form.yelp_id.errors %}
                <span class="text-danger">{{ error }}</span>
                {% endfor %}
            </p>
        </div>
        <button type="submit" class="btn btn-primary">Edit Entry</button>
    </form>
    <div class="modal fade " id="search-yelp-modal" tabindex="-1" data-bs-backdrop="static" aria-labelledby="search-yelp-modal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" >Results</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <div class="spinner-border m-5" id="spinner" role="status">
                        <span class="sr-only">Loading...</span>
                    </div>
                </div>
                <div id="results">
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.6.3.slim.min.js"
  integrity="sha256-ZwqZIVdD3iXNyGHbSYdsmWP//UBokj2FHAxKuSBKDSo="
  crossorigin="anonymous"></script>
<script src="https://unpkg.com/axios/dist/axios.js"></script>
<script src="/static/entry.js"></script>
{% endblock %}

templates/entry_show.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5 border rounded shadow-sm">
    <div class="row">
        <div class="col col-md-4">
            {% set missing_image = 'https://static.vecteezy.com/system/resources/previews/004/141/669/original/no-photo-or-blank-image-icon-loading-images-or-missing-image-mark-image-not-available-or-image-coming-soon-sign-simple-nature-silhouette-in-frame-isolated-illustration-vector.jpg'%}
            <img src={{restaurant.get('img_url') or missing_image}} class='img-fluid'/>
        </div>
        <div class="col col-md-8">
            {% if restaurant.get('url') %}
                <a href='{{restaurant.get("url")}}' class="h1 d-inline text-decoration-none" target="_blank" rel="noopener noreferrer">{{restaurant.get('name')}}</a>
            {% else %}
                <div class="h1 d-inline mb-1">{{restaurant.get('name')}}</div>
            {% endif %}
            {% if ratingsHTML %}<div class="d-block mb-2"><span class="text-danger mb-1">{{ratingsHTML|safe}}</span><span class="mb-1"> {{restaurant.get('review_count', 0)}} reviews</span></div>{% endif %}
            <div class="mb-2"><a class="btn btn-primary" href="{{url_for('calendar.edit_entry_page', entry_id=entry.id)}}">Edit</a>
                <form class="d-inline" method="POST" action="{{url_for('calendar.delete_entry', entry_id=entry.id)}}" id="delete-btn">
                    <button class="btn btn-danger" type="submit">Delete</button>
                </form></div>
            {% if restaurant.get('display_address') %}
            <p class="h5">
                {% for line in restaurant.get('display_address')%}
                {{line}}<br>
                {% endfor %}
                
                {% if restaurant.get('phone')%}
                {{restaurant.get('phone')}}
                {% endif %}
            </p>
            {% endif %}
            <div class="text-secondary">Date</div>
            <p class="h5">{{entry.date.strftime('%b %d, %Y')}}</p>
            {% if entry.amount %}
            <div class="text-secondary">Amount</div>
            <p class="h5">${{'%0.2f'|format(entry.amount)}}</p>
            {% endif %}
            <table class="table table-light table-striped border mt-4">
                <thead>
                    <tr><td class="table-light" colspan="2"><h5>Recent Visits</h5></td></tr>
                </thead>
                <tbody>
                {% for entry in recent_entries %}
                    <tr >
                        <td>{{entry.date.strftime("%B %d, %Y")}}</td>
                        <td>${{"%.2f"|format(entry.amount)}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script
  src="https://code.jquery.com/jquery-3.6.3.slim.min.js"
  integrity="sha256-ZwqZIVdD3iXNyGHbSYdsmWP//UBokj2FHAxKuSBKDSo="
  crossorigin="anonymous"></script>
<script src="https://unpkg.com/axios/dist/axios.js"></script>
<script src="/static/entry.js"></script>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<form class="form-signin m-auto" action='/login' method='POST'>
    <h1 class="h3 mb-3 fw-normal text-center">Eat Out Tracker</h1>
    <div class="text-center my-3"><i class="fa-solid fa-utensils display-1 text-info"></i></div>
    <div class="form-group">
        {{ form.hidden_tag() }}
    
        {% for field in form
            if field.widget.input_type != 'hidden' %}
    
        {% if field.type == "BooleanField" %}
            {{ field(class_="form-check-control") }}
            {{ field.label }}
        {% else %}            
        <div class='form-floating'>
            {{ field(class_="form-control") }}
            {{ field.label }}
        </div>
        {% endif %}
    
        {% for error in field.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %}
        
    
        {% endfor %}
    </div>
    <button class="btn btn-primary my-3">Log In</button>
</form>
{% endblock %}

templates/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container profile_form rounded border mt-5">
    <form action='/profile' method='POST'>
        <h1 class="h3 mb-3 fw-normal text-center">{{user.username}}</h1>
        <div class="form-group">
            {{ form.hidden_tag() }}
    
            {{form.default_location.label}}
            {{form.default_location(class_="form-control")}}
        </div>
        <button class="btn btn-primary my-3">Update</button>
    </form>
</div>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% block content %}
<form class="form-signin m-auto" action='/signup' method='POST'>
    <h1 class="h3 mb-3 fw-normal text-center">Eat Out Tracker</h1>
    <div class="text-center my-3"><i class="fa-solid fa-utensils display-1 text-info"></i></div>
    <div class="form-group">
        {{ form.hidden_tag() }}
    
        {% for field in form
            if field.widget.input_type != 'hidden' %}
    
        {% if field.type == "BooleanField" %}
            {{ field(class_="form-check-control") }}
            {{ field.label }}
        {% else %}            
        <div class='form-floating'>
            {{ field(class_="form-control") }}
            {{ field.label }}
        </div>
        {% endif %}
    
        {% for error in field.errors %}
        <span class="text-danger">{{ error }}</span>
        {% endfor %}
        
    
        {% endfor %}
    </div>
    <button class="btn btn-primary my-3">Sign Up</button>
</form>
{% endblock %}